title = "Daniel Tedman"
baseURL = "https://dbtedman.github.io/"
languageCode = "en-us"
theme = "ananke"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[languages]
[languages.en]
title = "Daniel Tedman"
weight = 1
contentDir = "content/en"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
facebook = ""
twitter = ""
instagram = ""
youtube = ""
github = "https://github.com"
gitlab = ""
linkedin = "https://www.linkedin.com/in/dbtedman"
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
#featured_image = "/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2
