---
name: "ci-master"

on:
    push:
        branches:
            - master

env:
    CI: true

jobs:
    run:
        runs-on: "ubuntu-20.04"

        steps:
            - uses: "actions/checkout@v1"
              with:
                  submodules: true

            - name: "Prepare Node"
              uses: "actions/setup-node@v1"
              with:
                  node-version: "15.6.0"
                  extended: true

            - name: "Setup Hugo"
              uses: "peaceiris/actions-hugo@v2"
              with:
                  hugo-version: "0.81.0"

            - name: "Install"
              run: "yarn install --no-audit"

            - name: "Lint"
              run: "./bin/lint"

            - name: "Build"
              run: "hugo --minify"

            - name: "Deploy"
              uses: "peaceiris/actions-gh-pages@v2"
              env:
                  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  EXTERNAL_REPOSITORY: "dbtedman/dbtedman.github.io"
                  PUBLISH_BRANCH: "master"
                  PUBLISH_DIR: ./public
              with:
                  emptyCommits: false
                  commitMessage: ${{ github.event.head_commit.message }}
